### ISSUE TITLE
如何 仅对 InPrivate 中的页面启用扩展

### ISSUE THREAD

**Issue by I-love-study** [omegaee/my-fingerprint#12]
如题，希望能够增加仅对 InPrivate 页面启用扩展，而正常页面则不启用的方法

**Comment by Sunakier** [comment]
可以尝试使用浏览器的多用户配置文件替代，InPrivate模式并非为如此增量的需求设计的

**Comment by omegaee** [comment]
目前没有该计划，也许会在后续加入。 

你可以尝试使用`多用户配置`或`白名单功能`来完成。 

祝好 :wink:
