### ISSUE TITLE
A new solution about canvas fingerprint generation

### ISSUE THREAD

**Issue by Hosinoharu** [omegaee/my-fingerprint#13]
我在 [www.browserscan.net](https://www.browserscan.net/zh/canvas) 网站进行了测试，发现当前的 `canvas toDataURL` 指纹生成方式略有缺陷。

我觉得伪造指纹的核心在于：**不能随意修改 canvas 中的像素信息，除非编写指纹验证的开发者也不清楚具体的像素信息**。

# 问题说明

目前已知网站的反检测方式有以下几种：

- 先生成一个固定颜色的矩形，调用 `.toDataURL()`，然后检查该矩形的像素点是否发生变化，这样可以防范像素点修改。
- 或者重复生成固定颜色的矩形，比对它们的像素点与 `.toDataURL()` 的值。
- 根据 `.toDataURL()` 的值重新生成图片，读取像素点，然后与之前的像素点进行比对。

正因为网站开发者也清楚绘制了什么内容（比如用 `red` 颜色绘制矩形，像素点肯定是红色的），故而可以通过获取像素点信息、`.toDataURL()` 值进行验证，而项目的原方案是在 `.toDataURL()` 中修改像素点，这容易被检测。

经过测试，当网站调用 `.fillText()` 绘制文本时，不同浏览器的结果中，像素点信息有了差距（可能和字体的渲染等有关），**此时网站开发者也不清楚图形中的像素点的具体信息**，所以可以 `hook fillText()`，在网站写入文字时写入自定义的特征值。

# 新的解决方案

上面只是一种处理方式，但不够稳妥，下面是我觉得更稳妥的方式 —— **修改生成的图片的元数据**。

简单而言，在调用 `.toDataURL()` 时默认生成一个 `png` 图片的 `base64` 编码字符串，我们可以在这个图片中插入自定义的元数据信息，从而使 `.toDataURL()` 的值发生变化，并且**这种插入不会更改图片的像素信息**。

以下是我修改的代码，可以过掉 `BrowwerScan` 的检测。

1.   将 `base64` 格式的图片转为二进制。
2.   添加自定义信息。
3.   再补足一个 `png` 格式的结束标签，避免网站检测。

```js
fh.win.HTMLCanvasElement.prototype.toDataURL = new Proxy(fh.rawObjects.toDataURL, {
          apply: (target, thisArg, args: Parameters<typeof HTMLCanvasElement.prototype.toDataURL>) => {
            let src = target.apply(thisArg, args);
            const value = fh.getValue('other', 'canvas')
            if (value !== null) {
              // ===================== 修改部分 =========================
              let [prefix, data] = src.split(',');
              const type = args[0] || 'image/png';
              if (type === 'image/png') {
                // 在 png 格式的尾部加上自定义信息，然后补足一个新的 IEND 标签
                data = atob(data) + value.toString() + "\x00\x00\x00\x00IEND\xAE\x42\x60\x82";
                src = prefix + ',' + btoa(data);
              // ==============================================
              } else {
                let ctx = thisArg.getContext('2d');
                if (ctx !== null) {
                  let style = ctx.fillStyle;
                  ctx.fillStyle = 'rgba(0, 0, 0, 0.01)';
                  ctx.fillText(value, 0, 2)
                  ctx.fillStyle = style;
                  return target.apply(thisArg, args);
                }
              }
            }
            return src;
          }
        })
```

这也许和解析文件的机制有关（我也不确定）：**当解析到文件的结束标志时就不会继续解析**。所以在尾部插入信息不影响浏览器将这个新的 `base64` 字符串渲染成图片，也不会修改图片的像素点信息。

更完全的方式是将自定义的信息写入到 `png` 图片的注释区域等，具体可以见这里 [PNG Specification - Textual information](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html#C.Anc-text)。
当然，这种解决方案依然是可以被检测的，网站需要对图片进行格式解析、找出多余的东西。我想这个工作会很复杂，不同浏览器可能也会写入不同的数据。

**Comment by omegaee** [comment]
很棒的方案!

可以在不破坏原像素的情况下，改变canvas指纹特征。

对此我也进行了一些尝试。

但正如你所说的，这种解决方案依然可以被检测，而且是可逆的。

**原方案**
> 不可逆

**你的提案**
> 可逆但不易被检测

1. 直接添加IEND尾部情况下：

能被 `https://browserleaks.com/canvas` 检测出来
或者，简单的复原：
```ts
const getRawData = (canvas: HTMLCanvasElement) => {
  const IEND = "\x00\x00\x00\x00IEND\xAE\x42\x60\x82"
  const { 1: data } = canvas.toDataURL().split(',')
  const temp = atob(data)
  return btoa(temp.substring(0, temp.indexOf(IEND) + IEND.length))
}
```

2. 写到PNG某些数据块的情况下：

将噪音写到`iTXt`和`tEXt`块感觉还不错。
但很是复杂，且同样可以被去掉。


**因此**
先不做改动。

**Comment by Hosinoharu** [comment]
也许我忽略了一个重点问题：真的有必要对抗 "网站检测指纹是否被修改" 吗？如果项目的目标不包括 "对抗检测" 的话，确实不需要这么麻烦，一般情况下现阶段已经很不错了

**Comment by omegaee** [comment]
漂亮的解决方案！
能在混淆的同时能对抗检测。

我尝试了下，效果很好。

至少比项目当前采用方案好太多了。

我计划在下版本中采用你的解决方案。
感谢你的努力和贡献 😄

**Comment by Hosinoharu** [comment]
> > [#13 (comment)](https://github.com/omegaee/my-fingerprint/issues/13#issuecomment-2426957285)
> 
> 漂亮的解决方案！ 能在混淆的同时能对抗检测。
> 
> 我尝试了下，效果很好。
> 
> 至少比项目当前采用方案好太多了。
> 
> 我计划在下版本中采用你的解决方案。 感谢你的努力和贡献 😄

很高兴能帮上忙哟

**Comment by omegaee** [comment]
该策略已在新版本使用 -> [v2.2.3](https://github.com/omegaee/my-fingerprint/releases/tag/2.2.3)

**Comment by LXS2000** [comment]
你们想的都太多了，真理往往反而很简单，试试我的插件Cthulhujs

**Comment by Hosinoharu** [comment]
> 你们想的都太多了，真理往往反而很简单，试试我的插件Cthulhujs

我查看了你的插件实现，代码被压缩了，只好做出猜测。似乎是调用 `toDataURL()` 时，先交换像素点、生成新的 `toDataURL()` 值、然后将交换的像素点还原回去。这确实是一个巧妙的方式，也可以通过网站的测试，非常棒！
