### ISSUE TITLE
请给一个捐赠方式

### ISSUE THREAD

**Issue by Leowolf93** [omegaee/my-fingerprint#14]
非常好用，谢谢。

**Comment by omegaee** [comment]
感谢支持 -> [支持一下](https://github.com/omegaee/my-fingerprint?tab=readme-ov-file#%E6%94%AF%E6%8C%81%E4%B8%80%E4%B8%8B) <- 😄

**Comment by Leowolf93** [comment]
> 感谢支持 -> [支持一下](https://github.com/omegaee/my-fingerprint?tab=readme-ov-file#%E6%94%AF%E6%8C%81%E4%B8%80%E4%B8%8B) <- 😄

再次感谢，已捐赠！祝越来越好！！！！
