### ISSUE TITLE
似乎2.2.2版本的WebGL图像、PLUGINS、RECTS、 FONTS都不会发生任何变化

### ISSUE THREAD

**Issue by Leowolf93** [omegaee/my-fingerprint#15]
![image](https://github.com/user-attachments/assets/8944d0f5-dd8a-4010-9cd8-ec65f7d2005f)

已打开每个标签页随机值，但是似乎有的时候有效，有的时候无效，有的时候刷新后会变回原先的值。

请求修复，谢谢！

**Comment by omegaee** [comment]
WebGL确实存在随机值的问题
至于RECTS、 FONTS、PLUGINS，目前该插件并未对这些特征进行修改

WebGL特征问题我需要研究一下

**Comment by Leowolf93** [comment]
> WebGL确实存在随机值的问题 至于RECTS、 FONTS、PLUGINS，目前该插件并未对这些特征进行修改
> 
> WebGL特征问题我需要研究一下

好的谢谢，辛苦了！
期待RECTS、 FONTS、PLUGINS等的特征修改功能！

**Comment by omegaee** [comment]
WebGL问题已在新版本修复并优化 -> [v2.2.3](https://github.com/omegaee/my-fingerprint/releases/tag/2.2.3)

对于PLUGINS指纹：该指纹重复率很高，没必要混淆。

对于RECTS、 FONTS指纹：这两指纹变化范围不大，不会单独作为用户标识使用，通常与canvas、webgl等指纹结合使用。混淆的必要性也不高，对应的混淆或许会在后续版本加入。
