### ISSUE TITLE
WebGL指纹无法混淆

### ISSUE THREAD

**Issue by minusmulticoloredper** [omegaee/my-fingerprint#20]
https://www.browserscan.net/zh
不管是系统值还是标签页随机值，就算重启了浏览器，WebGL和WebGL Report仍然不变。

**Comment by omegaee** [comment]
我试了下，是随机的，没有问题

确保你使用的扩展是最新的 -> [latest](https://github.com/omegaee/my-fingerprint/releases/latest)
若是，你能提供其他更详细的信息么

**Comment by minusmulticoloredper** [comment]
我上传了一个视频，请看看为什么会这样。
[1.zip](https://github.com/user-attachments/files/18051735/1.zip)

**Comment by minusmulticoloredper** [comment]
是不是和浏览器的版本有关？

**Comment by omegaee** [comment]
我换了设备尝试，确实无法混淆

有时间研究下

**Comment by omegaee** [comment]
是webgl2的原因，下个版本解决
