### ISSUE TITLE
fingerprint.com

### ISSUE THREAD

**Issue by xyzchz** [omegaee/my-fingerprint#9]
rollbar.umd.min.js:952 Rollbar: RangeError: Maximum call stack size exceeded

**Comment by omegaee** [comment]
我访问`fingerprint.com`并没发现`RangeError: Maximum call stack size exceeded`异常，你尝试使用 [v2.2.1](https://github.com/omegaee/my-fingerprint/releases/tag/2.2.1) ，看看是否能解决你遇到的问题
